6295 Filtering on owner/operator column in account data not pulling a…
US-EPA-CAMD/easey-streaming-services pull request #151
Opened 2024-08-23 13:46 UTC by usmanahmederg

Ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/6295

Changes
Updated Filtering by Owner/Operator in order to return any associated accounts, allowances, and transactions.

2024-08-23 17:07 UTC, ergjustin requested changes

2024-08-23 17:07 UTC, ergjustin commented on src/constants/emissions-field-mappings.ts
> +  { ...propertyMetadata.emissions.userId.fieldLabels},
Is this are necessary changes for CAMPD?

2024-08-23 17:07 UTC, ergjustin commented on src/dto/annual-apportioned-emissions.dto.ts
> +  userId?: string;
Is this are necessary changes for CAMPD?

2024-08-23 17:07 UTC, ergjustin commented on src/utils/account-query-builder.ts
> +
This is what I would do if it were me.
Create new Regex function in `easey-common`  and apply where as need
like [this may change]
```
 public static newfunctionName(str: string): string {
    return `'((^${str}$)|([,][ ]*${str}$)|([,][ ]*${str}[,])|(^${str}[,])|(^${str} [(])|([|][ ]*${str} [(]))'`;
  }
```

2025-03-18 12:42 UTC, mark-hayward-erg commented
Closing this outdated PR.

2025-03-18 12:42 UTC, closed without merging